Parameters:
  MyBucketName:
    Type: String
    Description: Enter Bucket name
    Default: grp-5-git-actions-malhar

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName:
        Ref: MyBucketName
      
  