Parameters:
  MyBucketName:
    Type: String
    Description: Enter Bucket name
    DeletionPolicy: DELETE
    Default: grp-5-git-actions-malhar

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: MyBucketName
      
  