Parameters:
  MyBucketName:
    Type: String
    Description: Enter Bucket name
    Default: git-actions

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: MyBucketName
      
  